
---
apiVersion: v1
kind: Service
metadata:
  name: ruletarusa-client
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
      app: ruletarusa-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruletarusa-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruletarusa-client
  template:
    metadata:
      labels:
        app: ruletarusa-client
    spec:
      containers:
      - name: ruletarusa-client
        image: eduardopm12/ruleta_rusa-client:latest
        ports:
        - containerPort: 5000
